package eu.quickgdx.game.mechanics.level;

/**
 * Created by Veit on 28.04.2017.
 */
public enum Tiletype {
    FLOOR, NONWALKABLE, WALL, WALL_END_LEFT, WALL_END_RIGHT, WALL_END_BOTH,CEILING_NSEW, CEILING_N, CEILING_E, CEILING_W, CEILING_S, CEILING_NE, CEILING_NS, CEILING_NSE, CEILING_NSW, CEILING_NW, CEILING_NWE, CEILING_SE, CEILING_SW, CEILING_SWE, CEILING_WE
}
